(function dashboardModule(globalScope) {
  "use strict";

  const SNAPSHOT_SCHEMA = "eu5.before-after-dashboard.snapshot/v1";
  const PAIR_SCHEMA = "eu5.before-after-dashboard.pair/v1";
  const MONITORING_BUNDLE_SCHEMA = "eu5.monitoring-bundle/v1";
  const LIVE_FEED_SCHEMA = "eu5.monitoring-feed/v1";
  const CLASSIFICATIONS = new Set([
    "verified-snapshot-pair",
    "candidate-snapshot-pair",
    "fixture-example"
  ]);
  const FRESHNESS_VALUES = new Set(["fresh", "stale", "unknown"]);
  const VERIFICATION_VALUES = new Set(["verified", "unverified", "fixture"]);
  const SHA256_PATTERN = /^[0-9a-f]{64}$/;
  const CANONICAL_UTC_TIMESTAMP_PATTERN =
    /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{3}))?Z$/;
  const LIMITS = Object.freeze({
    MAX_FILE_BYTES: 1024 * 1024,
    MAX_STATE_DEPTH: 16,
    MAX_FIELDS_PER_SNAPSHOT: 2000,
    MAX_ARRAY_LENGTH: 250,
    MAX_RENDERED_ROWS: 2000
  });
  const MISSING = Symbol("missing");
  const TERMINAL_ACTION_STATES = new Set([
    "verified",
    "failed",
    "expired",
    "ambiguous",
    "execution_unknown",
    "rejected"
  ]);
  const UNKNOWN_ACTION_STATES = new Set([
    "ambiguous",
    "execution_unknown",
    "unknown"
  ]);
  const NAVIGATION_ACTION_PATTERN =
    /(?:^|\.)(?:open|focus|navigate|find)_[a-z0-9_]+$/i;
  const TRUSTED_TELEMETRY_EVIDENCE =
    "Typed telemetry matched externally authenticated campaign, capture-session and reviewed-manifest evidence.";
  const TRUSTED_CHECKPOINT_EVIDENCE =
    "Metadata-only observation of the newest save checkpoint.";
  const TRUSTED_HEALTH_EVIDENCE =
    "Local adapter status generated by the loopback-only monitoring server.";
  const TRUSTED_ACTION_EVIDENCE =
    "Independent signed verification recorded in append-only control ledger.";

  function isPlainObject(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      return false;
    }
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  }

  function assertNonEmptyString(value, path) {
    if (typeof value !== "string" || value.trim() === "") {
      throw new Error(`${path} must be a non-empty string`);
    }
  }

  function parseCanonicalUtcTimestamp(value, path) {
    assertNonEmptyString(value, path);
    const match = CANONICAL_UTC_TIMESTAMP_PATTERN.exec(value);
    if (!match) {
      throw new Error(
        `${path} must use canonical UTC form YYYY-MM-DDTHH:mm:ss(.sss)?Z`
      );
    }

    const [, yearText, monthText, dayText, hourText, minuteText, secondText] = match;
    const year = Number(yearText);
    const month = Number(monthText);
    const day = Number(dayText);
    const hour = Number(hourText);
    const minute = Number(minuteText);
    const second = Number(secondText);
    const isLeapYear = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
    const daysInMonth = [
      0,
      31,
      isLeapYear ? 29 : 28,
      31,
      30,
      31,
      30,
      31,
      31,
      30,
      31,
      30,
      31
    ];

    if (
      year === 0 ||
      month < 1 ||
      month > 12 ||
      day < 1 ||
      day > daysInMonth[month] ||
      hour > 23 ||
      minute > 59 ||
      second > 59
    ) {
      throw new Error(`${path} must be a calendar-valid UTC timestamp`);
    }

    const timestamp = Date.parse(value);
    if (!Number.isFinite(timestamp)) {
      throw new Error(`${path} is outside the supported timestamp range`);
    }
    return timestamp;
  }

  function assertSha256(value, path) {
    if (typeof value !== "string" || !SHA256_PATTERN.test(value)) {
      throw new Error(`${path} must be exactly 64 lowercase hexadecimal characters`);
    }
  }

  function validateStateBounds(state, path) {
    if (!isPlainObject(state)) {
      throw new Error(`${path} must be an object`);
    }

    const seen = new WeakSet();
    const stack = [{ value: state, depth: 0 }];
    let fieldCount = 0;

    while (stack.length > 0) {
      const { value, depth } = stack.pop();
      if (Array.isArray(value) || isPlainObject(value)) {
        if (depth > LIMITS.MAX_STATE_DEPTH) {
          throw new Error(
            `${path} exceeds maximum nesting depth ${LIMITS.MAX_STATE_DEPTH}`
          );
        }
        if (seen.has(value)) {
          throw new Error(`${path} must be a JSON tree without circular or shared references`);
        }
        seen.add(value);

        if (Array.isArray(value)) {
          if (value.length > LIMITS.MAX_ARRAY_LENGTH) {
            throw new Error(
              `${path} array exceeds maximum length ${LIMITS.MAX_ARRAY_LENGTH}`
            );
          }
          fieldCount += value.length;
          if (fieldCount > LIMITS.MAX_FIELDS_PER_SNAPSHOT) {
            throw new Error(
              `${path} exceeds maximum field count ${LIMITS.MAX_FIELDS_PER_SNAPSHOT}`
            );
          }
          for (let index = value.length - 1; index >= 0; index -= 1) {
            stack.push({ value: value[index], depth: depth + 1 });
          }
          continue;
        }

        const keys = Object.keys(value);
        for (let index = keys.length - 1; index >= 0; index -= 1) {
          const key = keys[index];
          if (key.length === 0 || key.includes(".")) {
            throw new Error(`${path} field keys must be non-empty and cannot contain "."`);
          }
          fieldCount += 1;
          if (fieldCount > LIMITS.MAX_FIELDS_PER_SNAPSHOT) {
            throw new Error(
              `${path} exceeds maximum field count ${LIMITS.MAX_FIELDS_PER_SNAPSHOT}`
            );
          }
          stack.push({ value: value[key], depth: depth + 1 });
        }
        continue;
      }

      const primitiveType = typeof value;
      if (
        value === null ||
        primitiveType === "string" ||
        primitiveType === "boolean" ||
        (primitiveType === "number" && Number.isFinite(value))
      ) {
        continue;
      }
      throw new Error(`${path} contains a value that is not valid finite JSON data`);
    }

    return { fieldCount };
  }

  function validateSnapshot(snapshot, expectedRole) {
    if (!isPlainObject(snapshot)) {
      throw new Error(`${expectedRole} snapshot must be an object`);
    }
    if (snapshot.schemaVersion !== SNAPSHOT_SCHEMA) {
      throw new Error(`${expectedRole}.schemaVersion must be ${SNAPSHOT_SCHEMA}`);
    }
    if (snapshot.role !== expectedRole) {
      throw new Error(`${expectedRole}.role must be "${expectedRole}"`);
    }
    assertNonEmptyString(snapshot.snapshotId, `${expectedRole}.snapshotId`);
    assertNonEmptyString(snapshot.captureSessionId, `${expectedRole}.captureSessionId`);
    assertNonEmptyString(snapshot.entityId, `${expectedRole}.entityId`);
    if (!isPlainObject(snapshot.adapter)) {
      throw new Error(`${expectedRole}.adapter must be an object`);
    }
    assertNonEmptyString(snapshot.adapter.id, `${expectedRole}.adapter.id`);
    assertNonEmptyString(snapshot.adapter.version, `${expectedRole}.adapter.version`);
    assertSha256(snapshot.rawContentSha256, `${expectedRole}.rawContentSha256`);
    assertSha256(
      snapshot.fieldDefinitionFingerprint,
      `${expectedRole}.fieldDefinitionFingerprint`
    );
    parseCanonicalUtcTimestamp(snapshot.capturedAt, `${expectedRole}.capturedAt`);
    if (snapshot.gameTime !== null && typeof snapshot.gameTime !== "string") {
      throw new Error(`${expectedRole}.gameTime must be a string or null`);
    }
    if (!isPlainObject(snapshot.source)) {
      throw new Error(`${expectedRole}.source must be an object`);
    }
    assertNonEmptyString(snapshot.source.label, `${expectedRole}.source.label`);
    assertNonEmptyString(snapshot.source.kind, `${expectedRole}.source.kind`);
    if (!FRESHNESS_VALUES.has(snapshot.source.freshness)) {
      throw new Error(`${expectedRole}.source.freshness must be fresh, stale, or unknown`);
    }
    if (!isPlainObject(snapshot.source.verification)) {
      throw new Error(`${expectedRole}.source.verification must be an object`);
    }
    if (!VERIFICATION_VALUES.has(snapshot.source.verification.status)) {
      throw new Error(
        `${expectedRole}.source.verification.status must be verified, unverified, or fixture`
      );
    }
    assertNonEmptyString(
      snapshot.source.verification.evidence,
      `${expectedRole}.source.verification.evidence`
    );
    validateStateBounds(snapshot.state, `${expectedRole}.state`);
    return snapshot;
  }

  function assertPairValuesMatch(before, after, path, accessor) {
    if (accessor(before) !== accessor(after)) {
      throw new Error(`${path} must match across before and after snapshots`);
    }
  }

  function validatePair(pair) {
    if (!isPlainObject(pair)) {
      throw new Error("Snapshot pair must be an object");
    }
    if (pair.schemaVersion !== PAIR_SCHEMA) {
      throw new Error(`schemaVersion must be ${PAIR_SCHEMA}`);
    }
    if (!CLASSIFICATIONS.has(pair.classification)) {
      throw new Error(
        "classification must be verified-snapshot-pair, candidate-snapshot-pair, or fixture-example"
      );
    }
    assertNonEmptyString(pair.displayLabel, "displayLabel");
    const before = validateSnapshot(pair.before, "before");
    const after = validateSnapshot(pair.after, "after");
    const verificationStatuses = [
      before.source.verification.status,
      after.source.verification.status
    ];
    if (before.snapshotId === after.snapshotId) {
      throw new Error("before.snapshotId and after.snapshotId must be unique");
    }
    assertPairValuesMatch(
      before,
      after,
      "captureSessionId",
      (snapshot) => snapshot.captureSessionId
    );
    assertPairValuesMatch(before, after, "entityId", (snapshot) => snapshot.entityId);
    assertPairValuesMatch(before, after, "adapter.id", (snapshot) => snapshot.adapter.id);
    assertPairValuesMatch(
      before,
      after,
      "adapter.version",
      (snapshot) => snapshot.adapter.version
    );
    assertPairValuesMatch(
      before,
      after,
      "fieldDefinitionFingerprint",
      (snapshot) => snapshot.fieldDefinitionFingerprint
    );
    if (pair.classification === "verified-snapshot-pair") {
      if (!verificationStatuses.every((status) => status === "verified")) {
        throw new Error("verified-snapshot-pair requires both snapshots to be verified");
      }
      if (
        before.source.freshness !== "fresh" ||
        after.source.freshness !== "fresh"
      ) {
        throw new Error("verified-snapshot-pair requires both snapshots to be fresh");
      }
      if (before.source.kind !== after.source.kind) {
        throw new Error(
          "verified-snapshot-pair requires source.kind to match across snapshots"
        );
      }
      if (before.rawContentSha256 === after.rawContentSha256) {
        throw new Error(
          "verified-snapshot-pair requires distinct rawContentSha256 values"
        );
      }
    }
    if (
      pair.classification === "fixture-example" &&
      !verificationStatuses.every((status) => status === "fixture")
    ) {
      throw new Error("fixture-example pairs must mark both snapshots as fixture");
    }
    if (
      pair.classification === "candidate-snapshot-pair" &&
      verificationStatuses.some((status) => status === "fixture")
    ) {
      throw new Error("candidate-snapshot-pair cannot contain fixture snapshots");
    }
    const beforeTimestamp = parseCanonicalUtcTimestamp(
      before.capturedAt,
      "before.capturedAt"
    );
    const afterTimestamp = parseCanonicalUtcTimestamp(after.capturedAt, "after.capturedAt");
    if (afterTimestamp <= beforeTimestamp) {
      throw new Error("after.capturedAt must be strictly later than before.capturedAt");
    }
    return {
      schemaVersion: pair.schemaVersion,
      classification: pair.classification,
      displayLabel: pair.displayLabel,
      before,
      after
    };
  }

  function flattenState(value) {
    validateStateBounds(value, "state");
    const target = new Map();
    const stack = [{ value, path: "" }];

    while (stack.length > 0) {
      const item = stack.pop();
      if (isPlainObject(item.value)) {
        const keys = Object.keys(item.value).sort().reverse();
        if (keys.length === 0 && item.path) {
          target.set(item.path, {});
        } else {
          for (const key of keys) {
            stack.push({
              value: item.value[key],
              path: item.path ? `${item.path}.${key}` : key
            });
          }
        }
      } else if (item.path) {
        target.set(item.path, item.value);
      }
    }
    return target;
  }

  function stableValue(value) {
    if (Array.isArray(value)) {
      return `[${value.map(stableValue).join(",")}]`;
    }
    if (isPlainObject(value)) {
      return `{${Object.keys(value)
        .sort()
        .map((key) => `${JSON.stringify(key)}:${stableValue(value[key])}`)
        .join(",")}}`;
    }
    return JSON.stringify(value);
  }

  function classifyField(beforeValue, afterValue) {
    if (
      beforeValue === MISSING ||
      afterValue === MISSING ||
      beforeValue === null ||
      afterValue === null ||
      typeof beforeValue === "undefined" ||
      typeof afterValue === "undefined"
    ) {
      return "unknown";
    }
    return stableValue(beforeValue) === stableValue(afterValue) ? "unchanged" : "changed";
  }

  function formatValue(value) {
    if (value === MISSING) {
      return "Not supplied";
    }
    if (value === null || typeof value === "undefined") {
      return "Unknown";
    }
    if (typeof value === "string") {
      return value;
    }
    if (typeof value === "number" || typeof value === "boolean") {
      return String(value);
    }
    return stableValue(value);
  }

  function compareStates(beforeState, afterState) {
    const beforeFields = flattenState(beforeState);
    const afterFields = flattenState(afterState);
    const paths = [...new Set([...beforeFields.keys(), ...afterFields.keys()])].sort((a, b) =>
      a.localeCompare(b)
    );
    if (paths.length > LIMITS.MAX_RENDERED_ROWS) {
      throw new Error(
        `Comparison exceeds maximum rendered rows ${LIMITS.MAX_RENDERED_ROWS}`
      );
    }
    const rows = paths.map((path) => {
      const before = beforeFields.has(path) ? beforeFields.get(path) : MISSING;
      const after = afterFields.has(path) ? afterFields.get(path) : MISSING;
      return {
        path,
        before: formatValue(before),
        after: formatValue(after),
        status: classifyField(before, after)
      };
    });
    const counts = rows.reduce(
      (result, row) => {
        result[row.status] += 1;
        return result;
      },
      { changed: 0, unchanged: 0, unknown: 0 }
    );
    return { rows, counts };
  }

  function emptyModel() {
    return {
      status: "awaiting",
      statusLabel: "Awaiting verified snapshots",
      message: "No snapshot data loaded. See README.md for the local data contract.",
      pair: null,
      comparison: { rows: [], counts: null }
    };
  }

  function validateMonitoringBundle(bundle) {
    if (!isPlainObject(bundle)) {
      throw new Error("Monitoring bundle must be an object");
    }
    if (bundle.schemaVersion !== MONITORING_BUNDLE_SCHEMA) {
      throw new Error(`schemaVersion must be ${MONITORING_BUNDLE_SCHEMA}`);
    }
    const allowedBundleKeys = new Set([
      "schemaVersion", "bundleId", "generatedAtUtc", "sourceMode", "records", "integrity"
    ]);
    for (const key of Object.keys(bundle)) {
      if (!allowedBundleKeys.has(key)) throw new Error(`Monitoring bundle contains unsupported top-level field ${key}`);
    }
    // A bundle is an observational local artifact. It deliberately has no
    // promotion path to the before/after dashboard's verified state.
    for (const key of ["bundleId", "generatedAtUtc", "sourceMode", "records", "integrity"]) {
      if (!(key in bundle)) {
        throw new Error(`Monitoring bundle requires ${key}`);
      }
    }
    assertNonEmptyString(bundle.bundleId, "bundleId");
    parseCanonicalUtcTimestamp(bundle.generatedAtUtc, "generatedAtUtc");
    if (bundle.sourceMode !== "offline-import") {
      throw new Error("sourceMode must be offline-import");
    }
    if (!Array.isArray(bundle.records) || bundle.records.length > LIMITS.MAX_RENDERED_ROWS) {
      throw new Error(`Monitoring bundle records must be an array with at most ${LIMITS.MAX_RENDERED_ROWS} entries`);
    }
    if (!isPlainObject(bundle.integrity)) {
      throw new Error("Monitoring bundle integrity must be an object");
    }
    for (const key of Object.keys(bundle.integrity)) {
      if (key !== "manifestSha256") throw new Error(`integrity contains unsupported field ${key}`);
    }
    if ("manifestSha256" in bundle.integrity) {
      assertSha256(bundle.integrity.manifestSha256, "integrity.manifestSha256");
    }
    const types = new Set(["llm_action_proposed", "llm_action_outcome", "nation_snapshot", "game_event", "health"]);
    const recordIds = new Set();
    const sequences = new Set();
    let previousSequence = -1;
    for (const [index, record] of bundle.records.entries()) {
      const path = `records[${index}]`;
      if (!isPlainObject(record)) throw new Error(`${path} must be an object`);
      const allowedRecordKeys = new Set(["recordId", "recordType", "occurredAtUtc", "recordedAtUtc", "sequence", "correlationId", "captureSessionId", "subject", "provenance", "payload"]);
      for (const key of Object.keys(record)) {
        if (!allowedRecordKeys.has(key)) throw new Error(`${path} contains unsupported field ${key}`);
      }
      for (const key of ["recordId", "recordType", "occurredAtUtc", "recordedAtUtc", "sequence", "subject", "provenance", "payload"]) {
        if (!(key in record)) throw new Error(`${path} requires ${key}`);
      }
      assertNonEmptyString(record.recordId, `${path}.recordId`);
      if (recordIds.has(record.recordId)) {
        throw new Error(`${path}.recordId must be globally unique`);
      }
      recordIds.add(record.recordId);
      for (const optionalId of ["correlationId", "captureSessionId"]) {
        if (optionalId in record) assertNonEmptyString(record[optionalId], `${path}.${optionalId}`);
      }
      if (!types.has(record.recordType)) throw new Error(`${path}.recordType is not supported`);
      parseCanonicalUtcTimestamp(record.occurredAtUtc, `${path}.occurredAtUtc`);
      parseCanonicalUtcTimestamp(record.recordedAtUtc, `${path}.recordedAtUtc`);
      if (!Number.isSafeInteger(record.sequence) || record.sequence < 0) throw new Error(`${path}.sequence must be a non-negative integer`);
      if (sequences.has(record.sequence)) {
        throw new Error(`${path}.sequence must be globally unique`);
      }
      if (record.sequence <= previousSequence) {
        throw new Error(`${path}.sequence must be strictly increasing`);
      }
      sequences.add(record.sequence);
      previousSequence = record.sequence;
      if (!isPlainObject(record.subject) || !isPlainObject(record.provenance) || !isPlainObject(record.payload)) {
        throw new Error(`${path}.subject, provenance, and payload must be objects`);
      }
      const provenance = record.provenance;
      if (!isPlainObject(provenance.adapter) || !isPlainObject(provenance.verification)) throw new Error(`${path}.provenance adapter and verification must be objects`);
      assertNonEmptyString(provenance.adapter.id, `${path}.provenance.adapter.id`);
      assertNonEmptyString(provenance.adapter.version, `${path}.provenance.adapter.version`);
      if ("rawArtifactSha256" in provenance) assertSha256(provenance.rawArtifactSha256, `${path}.provenance.rawArtifactSha256`);
      if (!VERIFICATION_VALUES.has(provenance.verification.status)) throw new Error(`${path}.provenance.verification.status is invalid`);
      assertNonEmptyString(provenance.verification.evidence, `${path}.provenance.verification.evidence`);
      if (!FRESHNESS_VALUES.has(provenance.freshness)) throw new Error(`${path}.provenance.freshness is invalid`);
      validateStateBounds({ subject: record.subject, payload: record.payload }, path);
      validateMonitoringSafeValue(
        { subject: record.subject, provenance: record.provenance, payload: record.payload },
        path
      );
    }
    return bundle;
  }

  function validateLiveMonitoringFeed(feed) {
    if (!isPlainObject(feed)) {
      throw new Error("Live monitoring feed must be an object");
    }
    const allowedKeys = new Set([
      "schemaVersion", "feedId", "generatedAtUtc", "sourceMode", "records",
      "currentState", "currentObservations", "integrity"
    ]);
    for (const key of Object.keys(feed)) {
      if (!allowedKeys.has(key)) {
        throw new Error(`Live monitoring feed contains unsupported top-level field ${key}`);
      }
    }
    if (feed.schemaVersion !== LIVE_FEED_SCHEMA) {
      throw new Error(`schemaVersion must be ${LIVE_FEED_SCHEMA}`);
    }
    assertNonEmptyString(feed.feedId, "feedId");
    if (feed.sourceMode !== "local-live") {
      throw new Error("sourceMode must be local-live");
    }
    validateMonitoringBundle({
      schemaVersion: MONITORING_BUNDLE_SCHEMA,
      bundleId: feed.feedId,
      generatedAtUtc: feed.generatedAtUtc,
      sourceMode: "offline-import",
      records: feed.records,
      integrity: feed.integrity
    });
    for (const field of ["currentState", "currentObservations"]) {
      if (field in feed) {
        if (!isPlainObject(feed[field])) {
          throw new Error(`${field} must be an object`);
        }
        validateStateBounds(feed[field], field);
        validateMonitoringSafeValue(feed[field], field);
      }
    }
    return feed;
  }

  function validateMonitoringSafeValue(value, path) {
    // Normalize separators and case so `sessionToken`, `api_key`, and
    // `API-KEY` cannot bypass the local-import credential boundary.
    const forbiddenKey = /token|secret|password|cookie|authorization|apikey|credential|privatekey|bearer/i;
    const localPath = /(?:[a-z]:[\\/]|\\\\|file:)/i;
    const credentialValue =
      /\b(?:authorization\s*:\s*(?:bearer|basic)\s+\S+|bearer\s+[a-z0-9._~+/=-]{8,}|(?:api[\s_-]*key|access[\s_-]*token|refresh[\s_-]*token|password|secret)\s*[:=]\s*\S+)/i;
    const stack = [{ value, path }];
    while (stack.length) {
      const current = stack.pop();
      if (typeof current.value === "string" && localPath.test(current.value)) {
        throw new Error(`${current.path} must not contain local paths`);
      }
      if (typeof current.value === "string" && credentialValue.test(current.value)) {
        throw new Error(`${current.path} must not contain credential-like text`);
      }
      if (Array.isArray(current.value)) {
        current.value.forEach((item, index) => stack.push({ value: item, path: `${current.path}[${index}]` }));
      } else if (isPlainObject(current.value)) {
        for (const [key, item] of Object.entries(current.value)) {
          const normalizedKey = key.replace(/[^a-z0-9]/gi, "");
          if (forbiddenKey.test(normalizedKey)) throw new Error(`${current.path}.${key} must not contain secrets`);
          stack.push({ value: item, path: `${current.path}.${key}` });
        }
      }
    }
  }

  function monitoringRows(value) {
    if (Array.isArray(value)) {
      return value.slice(0, LIMITS.MAX_RENDERED_ROWS).map((item, index) => ({
        label: item && typeof item === "object" && !Array.isArray(item)
          ? (item.label || item.id || item.eventId || item.actionId || `#${index + 1}`)
          : `#${index + 1}`,
        value: item
      }));
    }
    return Object.keys(value || {}).sort().slice(0, LIMITS.MAX_RENDERED_ROWS).map((key) => ({
      label: key,
      value: value[key]
    }));
  }

  function buildMonitoringModel(bundleInput) {
    const bundle = validateMonitoringBundle(bundleInput);
    const byType = (type) => bundle.records.filter((record) => record.recordType === type);
    const warnings = [];
    if (!bundle.integrity.manifestSha256) warnings.push("No manifest SHA-256 was supplied; integrity is not independently confirmed.");
    if (bundle.records.some((record) => record.provenance.verification.status !== "verified")) warnings.push("Some records are unverified or fixture data; they are not real-state evidence.");
    if (bundle.records.some((record) => record.provenance.freshness !== "fresh")) warnings.push("Some records are stale or have unknown freshness.");
    return {
      bundle,
      isLive: false,
      ledger: monitoringRows(byType("llm_action_proposed").concat(byType("llm_action_outcome"))),
      health: monitoringRows(byType("health")),
      timeline: monitoringRows(bundle.records.filter((record) => record.recordType === "game_event" || record.recordType.startsWith("llm_action"))),
      nations: monitoringRows(byType("nation_snapshot")),
      provenance: monitoringRows(bundle.records.map((record) => ({
        label: record.recordId,
        adapter: record.provenance.adapter,
        verification: record.provenance.verification,
        freshness: record.provenance.freshness,
        rawArtifactSha256: record.provenance.rawArtifactSha256 || null
      }))),
      warnings
    };
  }

  function buildLiveMonitoringModel(feedInput) {
    const feed = validateLiveMonitoringFeed(feedInput);
    const model = buildMonitoringModel({
      schemaVersion: MONITORING_BUNDLE_SCHEMA,
      bundleId: feed.feedId,
      generatedAtUtc: feed.generatedAtUtc,
      sourceMode: "offline-import",
      records: feed.records,
      integrity: feed.integrity
    });
    model.bundle = feed;
    model.isLive = true;
    model.currentState = feed.currentState || null;
    model.currentObservations = feed.currentObservations || null;
    return model;
  }

  const HUMAN_METRICS = Object.freeze([
    { id: "treasury", label: "Treasury", group: "Economy", domain: "economy", keys: ["treasury"] },
    { id: "monthlyBalance", label: "Monthly balance", group: "Economy", domain: "economy", keys: ["monthlyBalance"] },
    { id: "income", label: "Income", group: "Economy", domain: "economy", keys: ["monthlyIncome"] },
    { id: "expenses", label: "Expenses", group: "Economy", domain: "economy", keys: ["monthlyExpenses"] },
    { id: "food", label: "Food balance", group: "Markets", domain: "markets", keys: ["foodBalance"] },
    { id: "marketAccess", label: "Market access", group: "Markets", domain: "markets", keys: ["marketAccess"] },
    { id: "tradeIncome", label: "Trade income", group: "Markets", domain: "markets", keys: ["tradeIncome"] },
    { id: "trackedGoods", label: "Tracked goods", group: "Markets", domain: "markets", collection: "goods", aggregate: "count", unit: "goods" },
    { id: "shortages", label: "Shortages", group: "Markets", domain: "markets", collection: "goods", aggregate: "negative-balance-count", unit: "goods" },
    { id: "diplomaticCapacity", label: "Diplomatic capacity", group: "Diplomacy", domain: "diplomacy", keys: ["diplomaticCapacity"] },
    { id: "warCount", label: "Wars", group: "Diplomacy", domain: "diplomacy", keys: ["warCount"] },
    { id: "atWar", label: "At war", group: "Diplomacy", domain: "diplomacy", keys: ["atWar"] },
    { id: "knownRelations", label: "Known relations", group: "Diplomacy", domain: "diplomacy", collection: "relations", aggregate: "count", unit: "countries" },
    { id: "relationWars", label: "Relations at war", group: "Diplomacy", domain: "diplomacy", collection: "relations", aggregate: "at-war-count", unit: "countries" },
    { id: "manpower", label: "Manpower", group: "Military", domain: "military", keys: ["manpower"] },
    { id: "armyStrength", label: "Army strength", group: "Military", domain: "military", keys: ["armyStrength"] },
    { id: "navyStrength", label: "Navy strength", group: "Military", domain: "military", keys: ["navyStrength", "navySize"] },
    { id: "trackedArmies", label: "Tracked armies", group: "Military", domain: "military", collection: "armies", aggregate: "count", unit: "armies" }
  ]);
  const OBSERVATION_DOMAIN_LABELS = Object.freeze({
    nation: "Nation",
    economy: "Economy",
    markets: "Markets",
    diplomacy: "Diplomacy",
    military: "Military"
  });
  const OBSERVATION_FIELD_LABELS = Object.freeze({
    atWar: "At war",
    isSubject: "Subject nation",
    countryTag: "Country tag",
    gameDateDisplay: "Game date",
    countryName: "Country name",
    gameDate: "Canonical game date",
    estimatedMonthlyIncomeDisplay: "Estimated monthly income",
    estimatedTradeTaxIncomeDisplay: "Estimated trade-tax income",
    treasuryDisplay: "Treasury",
    monthlyBalanceDisplay: "Monthly balance",
    monthlyBalanceClass: "Monthly balance status",
    treasuryClass: "Treasury status",
    monthlyBalance: "Monthly balance (numeric)",
    treasury: "Treasury (numeric)",
    monthlyIncomeTotal: "Monthly income (numeric)",
    hasMarketCenters: "Market centers detected",
    marketCount: "Market count",
    foodStockpile: "Food stockpile",
    capitalMarketIdDisplay: "Capital market ID",
    capitalMarketNameDisplay: "Capital market",
    capitalLocationMarketAccessDisplay: "Capital location market access",
    monthlyFoodBalanceDisplay: "Monthly food balance",
    foodStockpileDisplay: "Food stockpile",
    maxFoodStockpileDisplay: "Maximum food stockpile",
    foodStockpilePercentDisplay: "Food stockpile capacity",
    foodPriceDisplay: "Food price",
    totalValueTradedDisplay: "Total value traded",
    shortages: "Shortages",
    relations: "Relations",
    allies: "Allies",
    hasArmy: "Army present",
    hasNavy: "Navy present",
    canRaiseArmyLevies: "Can raise army levies",
    armySizeDisplay: "Army size",
    navySizeDisplay: "Navy size",
    manpowerDisplay: "Manpower",
    manpower: "Manpower (numeric)",
    supplyStatus: "Supply status"
  });
  const OBSERVATION_DOMAIN_ORDER = Object.freeze([
    "nation",
    "economy",
    "markets",
    "diplomacy",
    "military"
  ]);

  function displayMetricValue(value) {
    if (value === MISSING) return "No verified data";
    if (Array.isArray(value)) return value.length ? value.join(", ") : "None";
    if (typeof value === "number") {
      return new Intl.NumberFormat("en", { maximumFractionDigits: 2 }).format(value);
    }
    if (typeof value === "boolean") return value ? "Yes" : "No";
    if (isPlainObject(value)) return `${Object.keys(value).length} item(s)`;
    return String(value);
  }

  function aggregateVerifiedCollection(domain, definition) {
    if (!domain || !definition.collection || !Array.isArray(domain[definition.collection])) {
      return MISSING;
    }
    const collection = domain[definition.collection];
    if (definition.aggregate === "count") return collection.length;
    if (definition.aggregate === "negative-balance-count") {
      if (collection.some((item) =>
        !isPlainObject(item) ||
        !isPlainObject(item.balance) ||
        typeof item.balance.value !== "number"
      )) {
        return MISSING;
      }
      return collection.filter((item) =>
        item.balance.value < 0
      ).length;
    }
    if (definition.aggregate === "at-war-count") {
      return collection.filter((item) =>
        isPlainObject(item) && item.atWar === true
      ).length;
    }
    return MISSING;
  }

  function verifiedCurrentState(model) {
    const state = model.currentState;
    if (
      !isPlainObject(state) ||
      !["partial", "available"].includes(state.status) ||
      !isPlainObject(state.country) ||
      !isPlainObject(state.domains)
    ) {
      return null;
    }
    const domains = {};
    for (const [domainName, domain] of Object.entries(state.domains)) {
      if (!isPlainObject(domain) || typeof domain.recordId !== "string") continue;
      const source = model.bundle.records.find((record) =>
        record.recordId === domain.recordId &&
        record.recordType === "nation_snapshot" &&
        record.provenance.adapter.id === "eu5-control-bridge" &&
        record.provenance.adapter.version === "1" &&
        record.provenance.verification.status === "verified" &&
        record.provenance.verification.evidence === TRUSTED_TELEMETRY_EVIDENCE &&
        record.provenance.freshness === "fresh" &&
        record.subject.campaignId === state.campaignId &&
        record.subject.countryTag === state.country.tag &&
        record.subject.countryName === state.country.name &&
        (state.country.id === undefined || record.subject.countryId === state.country.id) &&
        record.payload.domain === domainName &&
        record.payload.gameDate === domain.gameDate &&
        record.payload.paused === domain.paused &&
        state.gameDate === domain.gameDate &&
        state.paused === domain.paused &&
        record.payload.capturedAtUtc === domain.capturedAtUtc &&
        stableValue(record.payload.metrics) === stableValue(domain.metrics) &&
        stableValue(record.payload.market) === stableValue(domain.market) &&
        stableValue(record.payload.goods) === stableValue(domain.goods) &&
        stableValue(record.payload.relations) === stableValue(domain.relations) &&
        stableValue(record.payload.armies) === stableValue(domain.armies)
      );
      if (source) domains[domainName] = domain;
    }
    if (!Object.keys(domains).length) return null;
    return { ...state, domains };
  }

  function humanTimelineEntry(record) {
    const payload = record.payload;
    let title = "Game observation";
    let detail = payload.label || payload.event || payload.procedure || "Recorded locally";
    let tone = "neutral";
    if (record.recordType === "llm_action_proposed") {
      title = `LLM proposed: ${payload.actionId || "unnamed action"}`;
      detail = payload.expectedVisibleResult || `Risk: ${payload.risk || "unknown"}`;
      tone = "proposed";
    } else if (record.recordType === "llm_action_outcome") {
      title = `Action: ${payload.lifecycleState || "outcome"}`;
      detail = payload.actualVisibleResult ||
        (payload.uiInputExecuted === true ? "Input dispatched" : "No input execution confirmed");
      tone = payload.verified === true ? "verified" : "outcome";
    } else if (payload.event === "latest-save-observed") {
      title = "Save checkpoint observed";
      detail = `${payload.saveFile || "EU5 save"} · ${payload.saveCount || 0} save(s) available`;
    } else if (payload.sourceRecordType) {
      title = payload.sourceRecordType.replaceAll("_", " ");
      detail = `${payload.procedure || "mod procedure"} · ${payload.status || "unknown result"}`;
    }
    return {
      id: record.recordId,
      title,
      detail,
      occurredAtUtc: record.occurredAtUtc,
      verification: record.provenance.verification.status,
      freshness: record.provenance.freshness,
      tone
    };
  }

  function actionSeries(records) {
    const series = new Map();
    for (const record of records) {
      if (
        !["llm_action_proposed", "llm_action_outcome"].includes(record.recordType) ||
        typeof record.correlationId !== "string"
      ) {
        continue;
      }
      if (!series.has(record.correlationId)) series.set(record.correlationId, []);
      series.get(record.correlationId).push(record);
    }
    return [...series.values()].map((items) =>
      items.sort((left, right) => {
        const time = Date.parse(left.recordedAtUtc) - Date.parse(right.recordedAtUtc);
        return time || left.sequence - right.sequence;
      })
    );
  }

  function terminalOutcome(series) {
    const outcomes = series.filter((record) => record.recordType === "llm_action_outcome");
    for (let index = outcomes.length - 1; index >= 0; index -= 1) {
      const state = outcomes[index].payload.lifecycleState;
      if (TERMINAL_ACTION_STATES.has(state) || state === "outcome_recorded") {
        return outcomes[index];
      }
    }
    return null;
  }

  function formatDuration(durationMs) {
    if (!Number.isFinite(durationMs) || durationMs < 0) return "Unavailable";
    if (durationMs < 1000) return `${Math.round(durationMs)} ms`;
    if (durationMs < 60_000) return `${(durationMs / 1000).toFixed(1)} s`;
    return `${(durationMs / 60_000).toFixed(1)} min`;
  }

  function hasTrustedActionVerification(record) {
    return Boolean(
      record &&
      record.provenance &&
      record.provenance.adapter &&
      record.provenance.adapter.id === "eu5-control-ledger" &&
      record.provenance.adapter.version === "1" &&
      record.provenance.verification &&
      record.provenance.verification.status === "verified" &&
      record.provenance.verification.evidence === TRUSTED_ACTION_EVIDENCE
    );
  }

  function formatActionOutcome(record, { allowTrustedVerification = false } = {}) {
    if (!record || !isPlainObject(record.payload)) return "Outcome unavailable";
    const lifecycleState =
      typeof record.payload.lifecycleState === "string"
        ? record.payload.lifecycleState
        : "unknown";
    const claimedOutcome =
      typeof record.payload.outcome === "string"
        ? record.payload.outcome
        : lifecycleState;
    const verified =
      allowTrustedVerification && hasTrustedActionVerification(record);
    const normalized = lifecycleState.replace(/_/g, " ").toUpperCase();
    let label;
    if (
      verified &&
      lifecycleState === "verified" &&
      claimedOutcome === "success"
    ) {
      label = "SUCCESS (verified)";
    } else if (["failed", "expired", "rejected"].includes(lifecycleState)) {
      label = `${normalized} (${verified ? "verified evidence" : "unverified"})`;
    } else if (UNKNOWN_ACTION_STATES.has(lifecycleState)) {
      label = `${normalized} (unverified)`;
    } else {
      label =
        `UNVERIFIED OUTCOME — claimed ${claimedOutcome.replace(/_/g, " ")}`;
    }
    const detail =
      typeof record.payload.actualVisibleResult === "string" &&
      record.payload.actualVisibleResult.trim() !== ""
        ? record.payload.actualVisibleResult
        : null;
    return detail ? `${label} — ${detail}` : label;
  }

  function buildOperationalSummary(
    records,
    { allowTrustedVerification = false } = {}
  ) {
    const actions = actionSeries(records);
    const completed = [];
    let unknownOutcomes = 0;
    for (const series of actions) {
      const proposal = series.find((record) => record.recordType === "llm_action_proposed");
      const terminal = terminalOutcome(series);
      if (!proposal || !terminal) continue;
      const durationMs =
        Date.parse(terminal.recordedAtUtc) - Date.parse(proposal.recordedAtUtc);
      if (Number.isFinite(durationMs) && durationMs >= 0) {
        completed.push({
          actionId: proposal.payload.actionId || "unnamed action",
          durationMs,
          terminal
        });
      }
      if (UNKNOWN_ACTION_STATES.has(terminal.payload.lifecycleState)) {
        unknownOutcomes += 1;
      }
    }

    const proposals = records
      .filter((record) => record.recordType === "llm_action_proposed")
      .sort((left, right) =>
        Date.parse(right.recordedAtUtc) - Date.parse(left.recordedAtUtc)
      );
    const latestProposal = proposals[0] || null;
    const activeProposal = proposals.find((proposal) => {
      const series = actions.find((candidate) => candidate.includes(proposal));
      return series && !terminalOutcome(series);
    }) || null;
    const outcomes = records
      .filter((record) => record.recordType === "llm_action_outcome")
      .sort((left, right) =>
        Date.parse(right.recordedAtUtc) - Date.parse(left.recordedAtUtc)
      );
    const latestOutcome = outcomes[0] || null;
    completed.sort((left, right) =>
      Date.parse(left.terminal.recordedAtUtc) -
      Date.parse(right.terminal.recordedAtUtc)
    );
    const latestCompleted = completed.at(-1) || null;
    const latestNavigation = completed
      .filter((item) => NAVIGATION_ACTION_PATTERN.test(item.actionId))
      .at(-1) || null;

    return {
      currentObjective: activeProposal
        ? activeProposal.payload.actionId || "Unnamed action"
        : "No active objective",
      objectiveDetail: activeProposal
        ? activeProposal.payload.expectedVisibleResult ||
          `Risk: ${activeProposal.payload.risk || "unknown"}`
        : latestProposal
          ? "The latest declared action has a recorded terminal outcome."
          : "Waiting for a declared LLM action.",
      lastAction: latestProposal
        ? latestProposal.payload.actionId || "Unnamed action"
        : "No action recorded",
      lastOutcome: latestOutcome
        ? formatActionOutcome(latestOutcome, { allowTrustedVerification })
        : "Outcome unavailable",
      actionLatency: latestCompleted
        ? formatDuration(latestCompleted.durationMs)
        : "Unavailable",
      navigationLatency: latestNavigation
        ? formatDuration(latestNavigation.durationMs)
        : "Unavailable",
      unknownOutcomes
    };
  }

  function latestVerifiedCheckpoint(records) {
    return records
      .filter((record) =>
        record.recordType === "game_event" &&
        record.payload.event === "latest-save-observed" &&
        record.provenance.adapter.id === "eu5-checkpoint-metadata" &&
        record.provenance.adapter.version === "1" &&
        record.provenance.verification.status === "verified" &&
        record.provenance.verification.evidence === TRUSTED_CHECKPOINT_EVIDENCE
      )
      .sort((left, right) =>
        Date.parse(right.occurredAtUtc) - Date.parse(left.occurredAtUtc)
      )[0] || null;
  }

  function bridgeHealthSummary(health) {
    const bridge = health.find((component) =>
      component.component === "structured-debug-log"
    );
    if (!bridge) return "Unknown";
    if (!bridge.verified) return "Unverified";
    const count = Number.isSafeInteger(bridge.count)
      ? ` · ${bridge.count} record(s)`
      : "";
    return `${bridge.status.replaceAll("-", " ")}${count}`;
  }

  function buildHumanMonitoringView(model) {
    const records = model.bundle.records;
    const current = verifiedCurrentState(model);

    const metrics = HUMAN_METRICS.map((definition) => {
      const domain = current && current.domains[definition.domain];
      let metric = MISSING;
      if (domain && isPlainObject(domain.metrics)) {
        for (const key of definition.keys || []) {
          if (isPlainObject(domain.metrics[key])) {
            metric = domain.metrics[key];
            break;
          }
        }
      }
      if (metric === MISSING && definition.collection) {
        const aggregate = aggregateVerifiedCollection(domain, definition);
        if (aggregate !== MISSING) {
          metric = { value: aggregate, unit: definition.unit };
        }
      }
      const value = metric === MISSING || metric.value === null ? MISSING : metric.value;
      return {
        ...definition,
        value: displayMetricValue(value),
        rawValue: value === MISSING ? null : value,
        unit: metric === MISSING ? null : metric.unit,
        status: value === MISSING ? "unknown" : "verified",
        delta: null
      };
    });

    const health = records
      .filter((record) => record.recordType === "health")
      .map((record) => ({
        component: record.payload.component || record.payload.sourceRecordType || "component",
        status: record.payload.status || "unknown",
        count: record.payload.recognizedRecordCount,
        verified:
          record.provenance.adapter.id === "eu5-local-monitoring-server" &&
          record.provenance.adapter.version === "1" &&
          record.provenance.verification.status === "verified" &&
          record.provenance.verification.evidence === TRUSTED_HEALTH_EVIDENCE
      }));
    const operations = buildOperationalSummary(records, {
      allowTrustedVerification: model.isLive === true
    });
    operations.bridgeHealth = bridgeHealthSummary(health);
    const checkpoint = latestVerifiedCheckpoint(records);
    const alerts = model.warnings.map((message) => ({ level: "warning", message }));
    if (!current) {
      alerts.unshift({
        level: "info",
        message: "No coherent, fresh, verified nation state is available. Country statistics remain unknown."
      });
    } else if (Array.isArray(current.warnings)) {
      alerts.unshift(...current.warnings.map((message) => ({ level: "info", message })));
    }
    alerts.push({
      level: "info",
      message: "Game speed telemetry is unavailable; the dashboard cannot infer speed from save metadata."
    });
    if (!checkpoint) {
      alerts.push({
        level: "info",
        message: "No verified save checkpoint metadata is available."
      });
    }
    for (const component of health) {
      if (!["available", "acknowledged"].includes(component.status)) {
        alerts.push({
          level: "warning",
          message: `${component.component}: ${component.status.replaceAll("-", " ")}.`
        });
      }
    }

    const observations = [];
    const observationState = model.currentObservations;
    if (
      isPlainObject(observationState) &&
      observationState.status === "partial" &&
      isPlainObject(observationState.domains)
    ) {
      for (const [domain, detail] of Object.entries(observationState.domains)) {
        if (!isPlainObject(detail) || !isPlainObject(detail.fields)) continue;
        for (const [field, observation] of Object.entries(detail.fields)) {
          if (!isPlainObject(observation)) continue;
          observations.push({
            domain,
            domainLabel: OBSERVATION_DOMAIN_LABELS[domain] || domain,
            field,
            fieldLabel: OBSERVATION_FIELD_LABELS[field] || field,
            value: observation.availability === "available"
              ? displayMetricValue(observation.value)
              : "Unavailable",
            availability: observation.availability || "unknown",
            reason: observation.reason || null,
            unit: observation.unit || null,
            updatedAtUtc:
              typeof detail.updatedAtUtc === "string" ? detail.updatedAtUtc : null
          });
        }
      }
    }
    observations.sort((left, right) => {
      const domainDifference =
        OBSERVATION_DOMAIN_ORDER.indexOf(left.domain) -
        OBSERVATION_DOMAIN_ORDER.indexOf(right.domain);
      if (domainDifference) return domainDifference;
      if (left.availability !== right.availability) {
        return left.availability === "available" ? -1 : 1;
      }
      return left.fieldLabel.localeCompare(right.fieldLabel);
    });
    const observedNation = Object.fromEntries(
      observations
        .filter((observation) =>
          observation.domain === "nation" &&
          observation.availability === "available"
        )
        .map((observation) => [observation.field, observation.value])
    );
    const hasObservedNationContext = Object.keys(observedNation).length > 0;
    const observationGroups = OBSERVATION_DOMAIN_ORDER
      .filter((domain) => domain !== "nation")
      .map((domain) => ({
        name: OBSERVATION_DOMAIN_LABELS[domain],
        domain,
        observations: observations.filter((observation) =>
          observation.domain === domain
        )
      }));

    return {
      isLive: model.isLive === true,
      generatedAtUtc: model.bundle.generatedAtUtc,
      country: current
        ? `${current.country.name} (${current.country.tag})`
        : observedNation.countryTag
          ? `Observed tag ${observedNation.countryTag}`
          : "Country unknown",
      gameDate: current && current.gameDate
        ? current.gameDate
        : observedNation.gameDateDisplay
          ? `Observed ${observedNation.gameDateDisplay}`
          : "Date unknown",
      pause: current && typeof current.paused === "boolean"
        ? current.paused ? "Paused" : "Running"
        : "Pause unknown",
      speed: "Speed unknown",
      nationVerification: current
        ? "verified"
        : hasObservedNationContext
          ? "unverified"
          : "unknown",
      objective: {
        current: operations.currentObjective,
        detail: operations.objectiveDetail,
        lastAction: operations.lastAction,
        lastOutcome: operations.lastOutcome
      },
      operations,
      checkpoint: checkpoint
        ? {
            name: checkpoint.payload.saveFile,
            detail:
              `${checkpoint.payload.saveCount || 0} save(s) · ` +
              `${checkpoint.provenance.freshness} · ${checkpoint.payload.lastWriteTimeUtc}`,
            freshness: checkpoint.provenance.freshness
          }
        : null,
      metrics,
      groups: ["Economy", "Markets", "Diplomacy", "Military"].map((group) => ({
        name: group,
        metrics: metrics.filter((metric) => metric.group === group)
      })),
      health,
      alerts,
      observations,
      observationGroups,
      timeline: records
        .filter((record) =>
          ["llm_action_proposed", "llm_action_outcome", "game_event"].includes(record.recordType)
        )
        .sort((left, right) =>
          Date.parse(right.occurredAtUtc) - Date.parse(left.occurredAtUtc)
        )
        .slice(0, 20)
        .map(humanTimelineEntry)
    };
  }

  function createLivePoller({
    fetchFn,
    onUpdate,
    onStatus = () => {},
    setTimeoutFn = setTimeout,
    clearTimeoutFn = clearTimeout,
    intervalMs = 2000,
    requestTimeoutMs = 1500,
    url = "/api/monitoring"
  }) {
    if (typeof fetchFn !== "function" || typeof onUpdate !== "function") {
      throw new TypeError("createLivePoller requires fetchFn and onUpdate");
    }
    let active = false;
    let nextTimer = null;
    const requestTimers = new Map();
    const requestControllers = new Map();
    const inFlightGenerations = new Set();
    let generation = 0;

    function schedule() {
      if (!active) return;
      nextTimer = setTimeoutFn(pollOnce, intervalMs);
    }

    async function pollOnce() {
      if (!active || inFlightGenerations.has(generation)) return;
      const pollGeneration = generation;
      inFlightGenerations.add(pollGeneration);
      const controller =
        typeof AbortController === "function" ? new AbortController() : null;
      if (controller) {
        requestControllers.set(pollGeneration, controller);
        requestTimers.set(
          pollGeneration,
          setTimeoutFn(() => controller.abort(), requestTimeoutMs)
        );
      }
      try {
        const response = await fetchFn(url, {
          cache: "no-store",
          headers: { Accept: "application/json" },
          ...(controller ? { signal: controller.signal } : {})
        });
        if (!response || !response.ok) {
          throw new Error(`HTTP ${response && response.status || "unavailable"}`);
        }
        const model = buildLiveMonitoringModel(await response.json());
        if (!active || pollGeneration !== generation) return;
        onUpdate(model);
        onStatus({ connected: true, generatedAtUtc: model.bundle.generatedAtUtc });
      } catch {
        if (active && pollGeneration === generation) {
          onStatus({ connected: false });
        }
      } finally {
        const requestTimer = requestTimers.get(pollGeneration);
        if (requestTimer !== undefined) clearTimeoutFn(requestTimer);
        requestTimers.delete(pollGeneration);
        requestControllers.delete(pollGeneration);
        inFlightGenerations.delete(pollGeneration);
        if (active && pollGeneration === generation) schedule();
      }
    }

    return {
      start() {
        if (active) return;
        active = true;
        generation += 1;
        void pollOnce();
      },
      stop() {
        active = false;
        generation += 1;
        if (nextTimer !== null) clearTimeoutFn(nextTimer);
        for (const requestTimer of requestTimers.values()) {
          clearTimeoutFn(requestTimer);
        }
        for (const controller of requestControllers.values()) {
          controller.abort();
        }
        requestTimers.clear();
        requestControllers.clear();
        nextTimer = null;
      },
      pollOnce,
      isActive() {
        return active;
      }
    };
  }

  function buildModel(pairInput) {
    const pair = validatePair(pairInput);
    const comparison = compareStates(pair.before.state, pair.after.state);
    const verificationStatuses = [
      pair.before.source.verification.status,
      pair.after.source.verification.status
    ];
    let status = "unverified";
    let statusLabel = "Loaded snapshots are not fully verified";

    if (pair.classification === "fixture-example") {
      status = "fixture";
      statusLabel = "Fixture / example — not real EU5 state";
    } else if (
      pair.classification === "verified-snapshot-pair" &&
      verificationStatuses.every((value) => value === "verified")
    ) {
      status = "ready";
      statusLabel = "Verified snapshots loaded";
    }

    return {
      status,
      statusLabel,
      message: `${pair.displayLabel}: ${comparison.rows.length} field(s) compared locally.`,
      pair,
      comparison
    };
  }

  function escapeHtml(value) {
    return String(value)
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#39;");
  }

  function setText(element, value) {
    element.textContent = value;
  }

  function setBadge(element, value, kind) {
    setText(element, value);
    element.className = `badge badge-${kind}`;
  }

  function renderSnapshot(elements, prefix, snapshot) {
    if (!snapshot) {
      setText(elements[`${prefix}Source`], "Not supplied");
      setText(elements[`${prefix}Captured`], "Unknown");
      setText(elements[`${prefix}GameTime`], "Unknown");
      setBadge(elements[`${prefix}Freshness`], "Unknown", "unknown");
      setBadge(elements[`${prefix}Verification`], "Unknown", "unknown");
      return;
    }

    setText(
      elements[`${prefix}Source`],
      `${snapshot.source.label} (${snapshot.source.kind}; ${snapshot.adapter.id}@${snapshot.adapter.version})`
    );
    setText(elements[`${prefix}Captured`], snapshot.capturedAt);
    setText(elements[`${prefix}GameTime`], snapshot.gameTime || "Unknown");
    setBadge(
      elements[`${prefix}Freshness`],
      snapshot.source.freshness,
      snapshot.source.freshness
    );
    setBadge(
      elements[`${prefix}Verification`],
      snapshot.source.verification.status,
      snapshot.source.verification.status
    );
    elements[`${prefix}Verification`].title = snapshot.source.verification.evidence;
  }

  function appendDetailRow(documentRef, tableBody, row) {
    const tr = documentRef.createElement("tr");
    const pathCell = documentRef.createElement("td");
    const beforeCell = documentRef.createElement("td");
    const afterCell = documentRef.createElement("td");
    const statusCell = documentRef.createElement("td");
    const status = documentRef.createElement("span");

    setText(pathCell, row.path);
    setText(beforeCell, row.before);
    setText(afterCell, row.after);
    setText(status, row.status);
    status.className = `detail-status detail-status-${row.status}`;
    statusCell.appendChild(status);
    tr.append(pathCell, beforeCell, afterCell, statusCell);
    tableBody.appendChild(tr);
  }

  function appendEmptyRow(documentRef, tableBody, message) {
    const tr = documentRef.createElement("tr");
    const td = documentRef.createElement("td");
    tr.className = "empty-row";
    td.colSpan = 4;
    setText(td, message);
    tr.appendChild(td);
    tableBody.appendChild(tr);
  }

  function renderMonitoringRows(documentRef, tableBody, rows, emptyMessage) {
    tableBody.replaceChildren();
    if (!rows.length) {
      const tr = documentRef.createElement("tr");
      const td = documentRef.createElement("td");
      td.colSpan = 2;
      setText(td, emptyMessage);
      tr.appendChild(td);
      tableBody.appendChild(tr);
      return;
    }
    for (const row of rows) {
      const tr = documentRef.createElement("tr");
      const label = documentRef.createElement("td");
      const value = documentRef.createElement("td");
      setText(label, row.label);
      setText(value, formatValue(row.value));
      tr.append(label, value);
      tableBody.appendChild(tr);
    }
  }

  function renderHumanMetricCards(documentRef, container, metrics) {
    container.replaceChildren();
    for (const metric of metrics) {
      const article = documentRef.createElement("article");
      article.className = `stat-card stat-card-${metric.status}`;
      const label = documentRef.createElement("span");
      label.className = "stat-card-label";
      setText(label, metric.label);
      const value = documentRef.createElement("strong");
      value.className = "stat-card-value";
      setText(value, metric.unit && metric.status === "verified"
        ? `${metric.value} ${metric.unit}`
        : metric.value);
      const source = documentRef.createElement("span");
      source.className = "stat-card-source";
      setText(source, metric.status === "verified" ? "Verified game export" : "Awaiting verified export");
      article.append(label, value, source);
      if (metric.delta !== null) {
        const delta = documentRef.createElement("span");
        delta.className = `metric-delta${metric.delta < 0 ? " metric-delta-negative" : ""}`;
        setText(delta, `${metric.delta > 0 ? "+" : ""}${displayMetricValue(metric.delta)} since prior snapshot`);
        article.appendChild(delta);
      }
      container.appendChild(article);
    }
  }

  function renderObservationCards(documentRef, container, observations) {
    container.replaceChildren();
    for (const observation of observations) {
      const article = documentRef.createElement("article");
      article.className =
        `observation-card observation-card-${observation.availability}`;
      const label = documentRef.createElement("span");
      label.className = "observation-card-label";
      setText(label, observation.fieldLabel);
      const value = documentRef.createElement("strong");
      value.className = "observation-card-value";
      setText(
        value,
        `${observation.value}${observation.unit ? ` ${observation.unit}` : ""}`
      );
      const source = documentRef.createElement("span");
      source.className = "observation-card-source";
      setText(
        source,
        observation.availability === "available"
          ? "Fresh bridge observation · unverified"
          : `Not exported · ${(observation.reason || "unknown reason").replaceAll("_", " ")}`
      );
      article.append(label, value, source);
      container.appendChild(article);
    }
  }

  function renderHumanMonitoringView(documentRef, elements, model) {
    const view = buildHumanMonitoringView(model);
    setText(elements.countryName, view.country);
    setText(elements.gameDate, view.gameDate);
    setText(elements.pauseState, view.pause);
    setText(elements.gameSpeed, view.speed);
    setBadge(
      elements.nationTrust,
      view.nationVerification === "verified"
        ? "Verified nation data"
        : view.nationVerification === "unverified"
          ? "Fresh unverified bridge observations"
          : "Nation data unknown",
      view.nationVerification
    );
    setText(elements.currentObjective, view.objective.current);
    setText(elements.objectiveDetail, view.objective.detail);
    setText(elements.lastAction, view.objective.lastAction);
    setText(elements.lastOutcome, view.objective.lastOutcome);
    setText(elements.actionLatency, view.operations.actionLatency);
    setText(elements.navigationLatency, view.operations.navigationLatency);
    setText(elements.unknownOutcomes, String(view.operations.unknownOutcomes));
    setText(elements.bridgeHealth, view.operations.bridgeHealth);
    setText(
      elements.checkpointName,
      view.checkpoint ? view.checkpoint.name : "No save observed"
    );
    setText(
      elements.checkpointDetail,
      view.checkpoint
        ? view.checkpoint.detail
        : "Checkpoint metadata unavailable"
    );
    const containers = {
      Economy: elements.economyCards,
      Markets: elements.marketsCards,
      Diplomacy: elements.diplomacyCards,
      Military: elements.militaryCards
    };
    const observationContainers = {
      Economy: elements.economyObservations,
      Markets: elements.marketsObservations,
      Diplomacy: elements.diplomacyObservations,
      Military: elements.militaryObservations
    };
    for (const group of view.groups) {
      renderHumanMetricCards(documentRef, containers[group.name], group.metrics);
    }
    for (const group of view.observationGroups) {
      const container = observationContainers[group.name];
      renderObservationCards(documentRef, container, group.observations);
      container.parentElement.hidden = group.observations.length === 0;
    }

    elements.humanAlerts.replaceChildren();
    for (const alert of view.alerts) {
      const item = documentRef.createElement("li");
      item.className = `alert-item alert-item-${alert.level}`;
      setText(item, alert.message);
      elements.humanAlerts.appendChild(item);
    }
    elements.alertRegion.hidden = view.alerts.length === 0;

    elements.humanObservations.replaceChildren();
    for (const observation of view.observations) {
      const item = documentRef.createElement("li");
      item.className = "observation-item";
      const title = documentRef.createElement("strong");
      setText(title, `${observation.domainLabel}: ${observation.fieldLabel}`);
      const value = documentRef.createElement("span");
      setText(
        value,
        `${observation.value}${observation.unit ? ` ${observation.unit}` : ""}` +
        `${observation.reason ? ` · ${observation.reason.replaceAll("_", " ")}` : ""}`
      );
      item.append(title, value);
      elements.humanObservations.appendChild(item);
    }
    elements.observationPanel.hidden = view.observations.length === 0;

    elements.humanTimeline.replaceChildren();
    if (!view.timeline.length) {
      const empty = documentRef.createElement("li");
      empty.className = "empty-row";
      setText(empty, "No LLM actions or game events recorded yet.");
      elements.humanTimeline.appendChild(empty);
    }
    for (const entry of view.timeline) {
      const item = documentRef.createElement("li");
      item.className = `timeline-item timeline-item-${entry.tone}`;
      const dot = documentRef.createElement("span");
      dot.className = "timeline-dot";
      dot.setAttribute("aria-hidden", "true");
      const copy = documentRef.createElement("div");
      const title = documentRef.createElement("strong");
      title.className = "timeline-title";
      setText(title, entry.title);
      const detail = documentRef.createElement("span");
      detail.className = "timeline-detail";
      setText(detail, entry.detail);
      copy.append(title, detail);
      const meta = documentRef.createElement("span");
      meta.className = "timeline-meta";
      setText(meta, `${entry.occurredAtUtc} · ${entry.verification} · ${entry.freshness}`);
      item.append(dot, copy, meta);
      elements.humanTimeline.appendChild(item);
    }

    elements.humanHealth.replaceChildren();
    if (!view.health.length) {
      const empty = documentRef.createElement("li");
      setText(empty, "No component health records.");
      elements.humanHealth.appendChild(empty);
    }
    for (const component of view.health) {
      const item = documentRef.createElement("li");
      item.className = "health-item";
      const name = documentRef.createElement("span");
      name.className = "health-name";
      setText(name, component.component.replaceAll("-", " "));
      const state = documentRef.createElement("span");
      const good = component.status === "available" && component.verified;
      state.className = `health-state${good ? " health-state-good" : ""}`;
      setText(
        state,
        `${component.status.replaceAll("-", " ")}${Number.isSafeInteger(component.count) ? ` · ${component.count}` : ""}`
      );
      item.append(name, state);
      elements.humanHealth.appendChild(item);
    }
    setText(elements.freshnessLabel, `Feed generated ${view.generatedAtUtc}`);
  }

  function renderMonitoringModel(documentRef, elements, model) {
    elements.monitoringPanel.hidden = !model;
    if (!model) return;
    renderHumanMonitoringView(documentRef, elements, model);
    const sourceId = model.bundle.bundleId || model.bundle.feedId;
    const sourceLabel = model.isLive
      ? "loopback live feed; observational only"
      : "offline import only";
    setText(
      elements.monitoringSummary,
      `${sourceId}: ${model.bundle.records.length} local record(s); ${sourceLabel}.`
    );
    elements.monitoringWarnings.replaceChildren();
    for (const warning of model.warnings) {
      const item = documentRef.createElement("li");
      setText(item, warning);
      elements.monitoringWarnings.appendChild(item);
    }
    renderMonitoringRows(documentRef, elements.ledgerBody, model.ledger, "No action ledger records.");
    renderMonitoringRows(documentRef, elements.healthBody, model.health, "No health records.");
    renderMonitoringRows(documentRef, elements.timelineBody, model.timeline, "No action or game-event records.");
    renderMonitoringRows(documentRef, elements.nationBody, model.nations, "No nation snapshots.");
    renderMonitoringRows(documentRef, elements.provenanceBody, model.provenance, "No provenance records.");
  }

  function renderModel(documentRef, elements, model, filter) {
    setText(elements.overallStatus, model.statusLabel);
    elements.overallStatus.className = `status status-${model.status}`;
    setText(elements.inputMessage, model.message);
    elements.inputMessage.classList.remove("input-message-error");

    const pair = model.pair;
    renderSnapshot(elements, "before", pair && pair.before);
    renderSnapshot(elements, "after", pair && pair.after);

    const isFixture = Boolean(pair && pair.classification === "fixture-example");
    elements.fixtureWarning.hidden = !isFixture;
    setText(elements.fixtureLabel, isFixture ? pair.displayLabel : "");

    const counts = model.comparison.counts;
    setText(elements.changedCount, counts ? String(counts.changed) : "—");
    setText(elements.unchangedCount, counts ? String(counts.unchanged) : "—");
    setText(elements.unknownCount, counts ? String(counts.unknown) : "—");

    elements.detailBody.replaceChildren();
    const selectedFilter = filter || "all";
    const visibleRows = model.comparison.rows.filter(
      (row) => selectedFilter === "all" || row.status === selectedFilter
    );
    if (visibleRows.length === 0) {
      const message = pair
        ? `No ${selectedFilter === "all" ? "" : `${selectedFilter} `}fields to display.`
        : "Awaiting verified snapshots. No game-state values are loaded.";
      appendEmptyRow(documentRef, elements.detailBody, message);
      return;
    }
    for (const row of visibleRows) {
      appendDetailRow(documentRef, elements.detailBody, row);
    }
  }

  async function readJsonFile(file) {
    if (
      !file ||
      !Number.isSafeInteger(file.size) ||
      file.size < 0 ||
      typeof file.text !== "function"
    ) {
      throw new Error("Selected input is not a valid local file");
    }
    if (file.size > LIMITS.MAX_FILE_BYTES) {
      throw new Error(
        `${file.name || "Selected file"} exceeds maximum size ${LIMITS.MAX_FILE_BYTES} bytes`
      );
    }

    const text = await file.text();
    const actualBytes = new TextEncoder().encode(text).byteLength;
    if (actualBytes > LIMITS.MAX_FILE_BYTES) {
      throw new Error(
        `${file.name || "Selected file"} exceeds maximum size ${LIMITS.MAX_FILE_BYTES} bytes`
      );
    }
    try {
      return JSON.parse(text);
    } catch (error) {
      throw new Error(`${file.name || "Selected file"}: invalid JSON (${error.message})`);
    }
  }

  function collectElements(documentRef) {
    return {
      overallStatus: documentRef.getElementById("overall-status"),
      inputMessage: documentRef.getElementById("input-message"),
      fixtureWarning: documentRef.getElementById("fixture-warning"),
      fixtureLabel: documentRef.getElementById("fixture-label"),
      beforeSource: documentRef.getElementById("before-source"),
      beforeCaptured: documentRef.getElementById("before-captured"),
      beforeGameTime: documentRef.getElementById("before-game-time"),
      beforeFreshness: documentRef.getElementById("before-freshness"),
      beforeVerification: documentRef.getElementById("before-verification"),
      afterSource: documentRef.getElementById("after-source"),
      afterCaptured: documentRef.getElementById("after-captured"),
      afterGameTime: documentRef.getElementById("after-game-time"),
      afterFreshness: documentRef.getElementById("after-freshness"),
      afterVerification: documentRef.getElementById("after-verification"),
      changedCount: documentRef.getElementById("changed-count"),
      unchangedCount: documentRef.getElementById("unchanged-count"),
      unknownCount: documentRef.getElementById("unknown-count"),
      detailBody: documentRef.getElementById("detail-body"),
      monitoringPanel: documentRef.getElementById("monitoring-panel"),
      monitoringSummary: documentRef.getElementById("monitoring-summary"),
      monitoringWarnings: documentRef.getElementById("monitoring-warnings"),
      ledgerBody: documentRef.getElementById("ledger-body"),
      healthBody: documentRef.getElementById("health-body"),
      timelineBody: documentRef.getElementById("timeline-body"),
      nationBody: documentRef.getElementById("nation-body"),
      provenanceBody: documentRef.getElementById("provenance-body"),
      liveStatus: documentRef.getElementById("live-status"),
      countryName: documentRef.getElementById("country-name"),
      gameDate: documentRef.getElementById("game-date"),
      pauseState: documentRef.getElementById("pause-state"),
      gameSpeed: documentRef.getElementById("game-speed"),
      nationTrust: documentRef.getElementById("nation-trust"),
      currentObjective: documentRef.getElementById("current-objective"),
      objectiveDetail: documentRef.getElementById("objective-detail"),
      lastAction: documentRef.getElementById("last-action"),
      lastOutcome: documentRef.getElementById("last-outcome"),
      checkpointName: documentRef.getElementById("checkpoint-name"),
      checkpointDetail: documentRef.getElementById("checkpoint-detail"),
      actionLatency: documentRef.getElementById("action-latency"),
      navigationLatency: documentRef.getElementById("navigation-latency"),
      unknownOutcomes: documentRef.getElementById("unknown-outcomes"),
      bridgeHealth: documentRef.getElementById("bridge-health"),
      freshnessLabel: documentRef.getElementById("freshness-label"),
      alertRegion: documentRef.getElementById("alert-region"),
      humanAlerts: documentRef.getElementById("human-alerts"),
      observationPanel: documentRef.getElementById("observation-panel"),
      humanObservations: documentRef.getElementById("human-observations"),
      economyCards: documentRef.getElementById("economy-cards"),
      marketsCards: documentRef.getElementById("markets-cards"),
      diplomacyCards: documentRef.getElementById("diplomacy-cards"),
      militaryCards: documentRef.getElementById("military-cards"),
      economyObservations: documentRef.getElementById("economy-observations"),
      marketsObservations: documentRef.getElementById("markets-observations"),
      diplomacyObservations: documentRef.getElementById("diplomacy-observations"),
      militaryObservations: documentRef.getElementById("military-observations"),
      humanTimeline: documentRef.getElementById("human-timeline"),
      humanHealth: documentRef.getElementById("human-health")
    };
  }

  function initialize(documentRef) {
    const elements = collectElements(documentRef);
    const pairInput = documentRef.getElementById("pair-file");
    const beforeInput = documentRef.getElementById("before-file");
    const afterInput = documentRef.getElementById("after-file");
    const monitoringInput = documentRef.getElementById("monitoring-file");
    const resetButton = documentRef.getElementById("reset-button");
    const filter = documentRef.getElementById("status-filter");
    let currentModel = emptyModel();
    let individualSnapshots = { before: null, after: null };
    let monitoringModel = null;
    let livePoller = null;

    function render() {
      renderModel(documentRef, elements, currentModel, filter.value);
      renderMonitoringModel(documentRef, elements, monitoringModel);
    }

    function showError(error) {
      currentModel = emptyModel();
      render();
      setText(elements.inputMessage, `Cannot compare snapshots: ${error.message}`);
      elements.inputMessage.classList.add("input-message-error");
    }

    pairInput.addEventListener("change", async () => {
      const file = pairInput.files && pairInput.files[0];
      if (!file) {
        return;
      }
      try {
        currentModel = buildModel(await readJsonFile(file));
        individualSnapshots = { before: null, after: null };
        beforeInput.value = "";
        afterInput.value = "";
        render();
      } catch (error) {
        showError(error);
      }
    });

    async function loadIndividual(role, file) {
      if (!file) {
        individualSnapshots[role] = null;
        currentModel = emptyModel();
        currentModel.message = `Waiting for a valid ${role === "before" ? "after" : "before"} snapshot.`;
        render();
        return;
      }
      try {
        individualSnapshots[role] = validateSnapshot(await readJsonFile(file), role);
        pairInput.value = "";
        if (individualSnapshots.before && individualSnapshots.after) {
          currentModel = buildModel({
            schemaVersion: PAIR_SCHEMA,
            classification: "candidate-snapshot-pair",
            displayLabel: "Individually supplied snapshot pair",
            before: individualSnapshots.before,
            after: individualSnapshots.after
          });
        } else {
          currentModel = emptyModel();
          currentModel.message = `Valid ${role} snapshot loaded; waiting for ${
            role === "before" ? "after" : "before"
          } snapshot.`;
        }
        render();
      } catch (error) {
        individualSnapshots[role] = null;
        showError(error);
      }
    }

    beforeInput.addEventListener("change", () =>
      loadIndividual("before", beforeInput.files && beforeInput.files[0])
    );
    afterInput.addEventListener("change", () =>
      loadIndividual("after", afterInput.files && afterInput.files[0])
    );
    monitoringInput.addEventListener("change", async () => {
      const file = monitoringInput.files && monitoringInput.files[0];
      if (!file) return;
      try {
        if (livePoller) livePoller.stop();
        monitoringModel = buildMonitoringModel(await readJsonFile(file));
        render();
      } catch (error) {
        monitoringModel = null;
        render();
        setText(elements.inputMessage, `Cannot load monitoring bundle: ${error.message}`);
        elements.inputMessage.classList.add("input-message-error");
      }
    });
    filter.addEventListener("change", render);
    resetButton.addEventListener("click", () => {
      currentModel = emptyModel();
      individualSnapshots = { before: null, after: null };
      pairInput.value = "";
      beforeInput.value = "";
      afterInput.value = "";
      monitoringInput.value = "";
      monitoringModel = null;
      filter.value = "all";
      render();
      if (livePoller) livePoller.start();
    });

    render();

    const locationRef = documentRef.defaultView && documentRef.defaultView.location;
    const isLoopback =
      locationRef &&
      (locationRef.hostname === "127.0.0.1" || locationRef.hostname === "localhost") &&
      /^https?:$/.test(locationRef.protocol);
    if (isLoopback && typeof documentRef.defaultView.fetch === "function") {
      livePoller = createLivePoller({
        fetchFn: documentRef.defaultView.fetch.bind(documentRef.defaultView),
        onUpdate(model) {
          monitoringModel = model;
          if (!currentModel.pair) {
            currentModel.message =
              "Live monitoring is active. Before/after snapshot comparison remains optional.";
          }
          render();
        },
        onStatus(status) {
          if (!elements.liveStatus) return;
          if (status.connected) {
            setText(
              elements.liveStatus,
              `Live feed connected · refreshed ${status.generatedAtUtc}`
            );
            elements.liveStatus.className = "status status-ready live-status";
          } else {
            setText(
              elements.liveStatus,
              "Live feed disconnected · retaining last valid records"
            );
            elements.liveStatus.className = "status status-unverified live-status";
          }
        }
      });
      livePoller.start();
    } else if (elements.liveStatus) {
      setText(elements.liveStatus, "Offline file mode");
    }
  }

  const api = {
    SNAPSHOT_SCHEMA,
    PAIR_SCHEMA,
    MONITORING_BUNDLE_SCHEMA,
    LIVE_FEED_SCHEMA,
    LIMITS,
    buildModel,
    buildMonitoringModel,
    buildLiveMonitoringModel,
    buildHumanMonitoringView,
    classifyField,
    compareStates,
    emptyModel,
    escapeHtml,
    flattenState,
    formatValue,
    parseCanonicalUtcTimestamp,
    readJsonFile,
    createLivePoller,
    validateStateBounds,
    validatePair,
    validateMonitoringBundle,
    validateLiveMonitoringFeed,
    validateSnapshot
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }
  if (globalScope) {
    globalScope.EU5BeforeAfterDashboard = api;
  }
  if (typeof document !== "undefined") {
    document.addEventListener("DOMContentLoaded", () => initialize(document));
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
